from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from openai import OpenAI

from src.runners.run_modules import run_modules


PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODULES_ROOT = PROJECT_ROOT / "modules"
OUTPUTS_ROOT = PROJECT_ROOT / "outputs"
REPORTS_ROOT = PROJECT_ROOT / "reports"

MODEL = "here"
SYSTEM_PROMPT = (
    "You are a concise cybersecurity analyst. "
    "Analyze the supplied files as the source of truth and make no other assumptions. "
    "Respect provenance metadata: sample or demo data is for testing only and must not produce security conclusions or action items. "
    "Imported logs are historical observations, not proof of compromise. "
    "Target-detection-only outputs are not service scans and must not be described as open-port findings. "
    "If SafeSniff output has mode='target_detection_only', provenance.active_network_scan=false, or total_tcp_connect_attempts_planned=0, state that no TCP service scan was run even if the selected profile name is 'thorough'. "
    "When DNS evidence contains lookalike, typo-squatted, login, password, invoice, payment, or document-sharing domains, classify the likely threat type such as phishing, credential theft, brand impersonation, or invoice fraud while stating that DNS logs alone do not prove compromise."
)
USER_PROMPT = (
    "Review the files and summarize what they contain. "
    "Triage the findings into a maximum of 5 actionable items to improve security in order of importance. "
    "This report should be understandable to a non technical user. "
    "If a file contains provenance.sample_data=true or provenance.data_origin='sample', mention it only as test data and exclude it from actionable items. "
    "When evidence is weak, say so plainly and do not invent risks. "
    "For suspicious DNS findings, name the suspicious domains, state the likely threat category, identify the affected host if present, and recommend concrete next steps such as checking browser history, warning the user, blocking the domains, and reviewing credentials. "
    "It must be in the following markdown format:\n"
    "## Summary\n"
    "- A brief summary of the overall findings.\n"
    "## Actionable Items\n"
    "- A numbered list of up to 5 actionable items, each with a brief explanation."
    "\n\nFor each actionable item, append a citation on the next line in this exact format:\n"
    "<|source_name, \"string to search for\"|>\n"
    "Use source_name as the input filename exactly as provided."
    "The search string must be an exact substring from the source file that supports the item."
    "If no citation applies, omit the citation line for that item."
)

client = OpenAI(
    api_key="not-needed",
    base_url="http://localhost:8033/v1",
)


def create_run_dirs(ts: datetime) -> tuple[Path, Path]:
    """Create output and report directories for the current run based on the timestamp."""
    date_path = Path(ts.strftime("%Y-%m-%dT%H:%M:%SZ").replace(":", "-"))

    output_dir = OUTPUTS_ROOT / date_path
    report_dir = REPORTS_ROOT

    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)
    return output_dir, report_dir


def collect_json_payload(json_files: list[Path], root_for_names: Path) -> list[dict[str, str]]:
    return [
        {
            "filename": str(json_file.relative_to(root_for_names)),
            "file_data": json_file.read_text(encoding="utf-8"),
        }
        for json_file in json_files
    ]


def analyze_with_llm(files: list[dict[str, str]]) -> str:
    if not files:
        return "No data files were generated by modules for this run."

    sections = [f"File: {f['filename']}\n{f['file_data']}" for f in files]
    module_prompt = "\n\n".join(sections)

    print("Analyzing with LLM...")

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"{USER_PROMPT}\n\n{module_prompt}",
            },
        ],
    )

    return response.choices[0].message.content or ""


def _build_body(report_body: str, files: list[dict[str, str]]) -> str:
    file_lookup = {item["filename"]: item["file_data"] for item in files}

    def _render_citation(source: str, search: str) -> list[str]:
        # Look up the source file content
        content = file_lookup.get(source)
        if content is None:
            return [f"[citation] {source}: source file not found"]

        # Search for the specified string in the content
        lines = content.splitlines()
        match_index = None
        for idx, line in enumerate(lines):
            if search in line:
                match_index = idx
                break
        if match_index is None:
            return [f"[citation] {source}: no match for {search}"]

        # Render the matching line with context and line numbers
        start = max(match_index - 1, 0)
        end = min(match_index + 1, len(lines) - 1)
        rendered: list[str] = [f"[citation] {source}:", "```"]
        for idx in range(start, end + 1):
            rendered.append(f"{idx + 1}: {lines[idx]}")
        rendered.append("```")
        return rendered

    cleaned_lines: list[str] = []
    for raw_line in report_body.splitlines():
        # Search for citation patterns
        line = raw_line.strip()
        if (line.startswith("<|") or line.startswith("<")) and (line.endswith("|>") or line.endswith(">")):
            inner = line[2:-2]
            parts = inner.split(",", 1)
            if len(parts) == 2:
                source = parts[0].strip()
                search = parts[1].strip()
                if search.startswith('"') and search.endswith('"') and len(search) >= 2:
                    search = search[1:-1]
                if source and search:
                    # Generate and display the citation for this item
                    cleaned_lines.append("")
                    cleaned_lines.extend(_render_citation(source, search))
                    cleaned_lines.append("")
        else:
            cleaned_lines.append(raw_line)

    return "\n".join(cleaned_lines).strip()


def save_report(
    ts: datetime,
    report_dir: Path,
    report_body: str,
    files: list[dict[str, str]],
    info: list[str],
) -> Path:
    print("Writing report...")

    cleaned_body = _build_body(report_body, files)

    report_path = report_dir / f"security_report_{ts.strftime('%Y-%m-%dT%H:%M:%SZ').replace(':', '-')}.md"

    header_lines = [
        "# Security Analysis Report\n",
        f"Generated (UTC): {ts}",
    ]

    header_lines.extend(["", "## Module Runner Information"])
    if info:
        header_lines.extend([f"- {item}" for item in info])
    else:
        header_lines.append("- No modules executed or no files generated.")

    header_lines.extend(["", "## Input Files"])
    if files:
        header_lines.extend([f"- {item['filename']}" for item in files])
    else:
        header_lines.append("- None")

    # Append the main report body generated by the LLM
    header_lines.extend(["", cleaned_body, ""])
    report_path.write_text("\n".join(header_lines), encoding="utf-8")

    return report_path


def run_assessment(
    *,
    demo: bool = False,
    verbose: bool = False,
    module_overrides: dict[str, dict[str, Any]] | None = None,
) -> Path | None:
    ts = datetime.now(UTC)
    output_dir, report_dir = create_run_dirs(ts)

    generic_overrides = {
        "demo": demo,
        "verbose": verbose,
    }

    generated_json_files, runner_info, runner_errors = run_modules(
        MODULES_ROOT,
        output_dir,
        module_overrides=module_overrides,
        generic_overrides=generic_overrides,
    )
    if runner_errors:
        print("\nModule Runner Errors:")
        for error in runner_errors:
            print(f"- {error}")
        print("Stopping execution due to module runner errors.")
        return None
    payload_files = collect_json_payload(generated_json_files, output_dir)
    report_body = analyze_with_llm(payload_files)
    report_path = save_report(ts, report_dir, report_body, payload_files, runner_info)

    print(f"\nReport saved to: {report_path}")
    return report_path
