from __future__ import annotations

import importlib.util
from datetime import UTC, datetime
from pathlib import Path
from typing import cast

from openai import OpenAI

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODULES_ROOT = PROJECT_ROOT / "modules"
OUTPUTS_ROOT = PROJECT_ROOT / "outputs"
REPORTS_ROOT = PROJECT_ROOT / "reports"

MODEL = "here"
SYSTEM_PROMPT = (
    "You are a concise cybersecurity analyst."
    "Analyze the supplied files as the source of truth and make no other assumptions."
)
USER_PROMPT = (
    "Review the files and summarize what they contain."
    "Triage the findings into a maximum of 5 actionable items to improve security in order of importance."
    "This report should be understandable to a non technical user."
    "It must be in the following markdown format:\n"
    "## Summary\n"
    "- A brief summary of the overall findings.\n"
    "## Actionable Items\n"
    "- A numbered list of up to 5 actionable items, each with a brief explanation."
)

client = OpenAI(
    api_key="not-needed",
    base_url="http://localhost:8033/v1",
)


def create_run_dirs(ts: datetime) -> tuple[Path, Path]:
    """Create output and report directories for the current run based on the timestamp."""
    date_path = Path(ts.strftime('%Y-%m-%dT%H:%M:%SZ').replace(':', '-'))

    output_dir = OUTPUTS_ROOT / date_path
    report_dir = REPORTS_ROOT

    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)
    return output_dir, report_dir


def _load_runner(module_dir: Path) -> type | None:
    """Dynamically load the Runner class from the module's runner.py file."""
    runner_path = module_dir / "runner.py"
    if not runner_path.exists():
        return None

    spec = importlib.util.spec_from_file_location(
        f"runner_{module_dir.name}", runner_path
    )
    if spec is None or spec.loader is None:
        return None

    print(f"Loading runner: {module_dir.name}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    runner_class = getattr(module, "Runner", None)
    if runner_class is not None:
        return cast(type, runner_class)
    return None


def run_modules(output_dir: Path) -> tuple[list[Path], list[str], list[str]]:
    generated_json_files: list[Path] = []
    info: list[str] = []
    errors: list[str] = []

    # Discover a sorted list of module directories.
    discover_module_dirs: list[Path] = []
    if MODULES_ROOT.exists():
        discover_module_dirs = sorted(
            [path for path in MODULES_ROOT.iterdir() if path.is_dir()]
        )

    # Iterate through each module
    for module_dir in discover_module_dirs:
        module_output_dir = output_dir / module_dir.name
        module_output_dir.mkdir(parents=True, exist_ok=True)

        runner_class = _load_runner(module_dir)
        if runner_class is None:
            continue

        try:
            runner_instance = runner_class()
            module_output_dir.mkdir(parents=True, exist_ok=True)
            module_files = runner_instance.run(module_output_dir, module_dir)
            generated_json_files.extend(
                [
                    file
                    for file in module_files
                    if file.suffix.lower() == ".json" and file.exists()
                ]
            )
            info.append(f"{module_dir.name}: {len(module_files)} files generated.")
        except Exception as exc:
            errors.append(f"{module_dir.name}: {exc}")

    return sorted(set(generated_json_files)), info, errors


def collect_json_payload(
    json_files: list[Path], root_for_names: Path
) -> list[dict[str, str]]:
    return [
        {
            "filename": str(json_file.relative_to(root_for_names)),
            "file_data": json_file.read_text(encoding="utf-8"),
        }
        for json_file in json_files
    ]


def analyze_with_llm(files: list[dict[str, str]]) -> str:
    if not files:
        return "No data files were generated by modules for this run."
    
    sections = [f"File: {f['filename']}\n{f['file_data']}" for f in files]
    module_prompt: str = "\n\n".join(sections)

    print("Analyzing with LLM...")

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"{USER_PROMPT}\n\n{module_prompt}",
            },
        ],
    )

    return response.choices[0].message.content or ""


def save_report(
    ts: datetime,
    report_dir: Path,
    report_body: str,
    files: list[dict[str, str]],
    info: list[str],
    errors: list[str],
) -> Path:
    print("Writing report...")

    report_path = (
        report_dir / f"security_report_{ts.strftime('%Y-%m-%dT%H:%M:%SZ').replace(':', '-')}.md"
    )

    header_lines = [
        "# Security Analysis Report\n",
        f"Generated (UTC): {ts}",
    ]

    # List information about the module runs
    header_lines.extend(["", "## Module Runner Information"])
    if info:
        header_lines.extend([f"- {item}" for item in info])
    else:
        header_lines.append("- No modules executed or no files generated.")

    # List files that were included in the analysis
    header_lines.extend(["", "## Input Files"])
    if files:
        header_lines.extend([f"- {item['filename']}" for item in files])
    else:
        header_lines.append("- None")

    # List any errors that occured during module execution
    header_lines.extend(["", "## Module Runner Errors"])
    if errors:
        header_lines.extend([f"- {error}" for error in errors])
    else:
        header_lines.append("- None")

    # Append the main report body generated by the LLM
    header_lines.extend(["", report_body.strip(), ""])
    report_path.write_text("\n".join(header_lines), encoding="utf-8")

    return report_path


def main() -> None:
    ts = datetime.now(UTC)
    output_dir, report_dir = create_run_dirs(ts) # Create output and report directories

    generated_json_files, runner_info, runner_errors = run_modules(output_dir)
    payload_files = collect_json_payload(generated_json_files, output_dir)
    report_body = analyze_with_llm(payload_files)
    report_path = save_report(ts, report_dir, report_body, payload_files, runner_info, runner_errors)

    print(f"\nReport saved to: {report_path}")
